import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import Navbar from "./components/Navbar";
import ReduxProvider from "./redux-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-100">
        <Navbar />
        <Toaster position="top-center" reverseOrder={false} />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
